config/routes.rb
Railsquebec::Application.routes.draw do
  scope "(:locale)", locale: /en|fr/, defaults: { locale: "fr" } do
    mount MinimalistCms::Engine, at: '/page'

    root to: 'minimalist_cms/pages#show'

    get "jobs/index"

    get "maps/index"

    devise_for :users

    resources :users
    resources :jobs
    resources :events
    resources :groups, only: :index
    resources :maps, only: [:index] do
      collection do
        get :users
        get :jobs
        get :events
      end
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

    if user
      if user.admin?
        can :manage, :all
      else
        can :create, :all
        can :manage, Event do |event|
          event.user == user
        end

        can :manage, Job do |job|
          job.user == user
        end
      end
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :pages

  attr_accessible :position, :title

  default_scope order(:position)
end

app/models/event.rb
class Event < ActiveRecord::Base
  include Addresseable

  default_scope { order("date DESC") }

  attr_accessible :city, :date, :description, :postal_code, :street, :title,
                  :website

  belongs_to :user

  validates :title,       presence: true
  validates :date,        presence: true
  validates :description, presence: true
  validates :postal_code, presence: true
  validates :street,      presence: true
  validates :city,        presence: true
  validates :user,        presence: true

  def to_s
    title
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  include Addresseable

  default_scope { order("created_at DESC") }

  attr_accessible :street, :city, :company_name, :description, :email,
                  :postal_code, :post_name, :website

  belongs_to :user

  validates :company_name, presence: true
  validates :email, presence: true
  validates :post_name, presence: true
  validates :street, presence: true
  validates :city, presence: true
  validates :postal_code, presence: true
  validates :description, presence: true

  def to_s
    post_name
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  acts_as_page
  translates :title, :slug, :meta_keywords, :meta_description

  belongs_to :category

  attr_accessible :position
end

app/models/user.rb
class User < ActiveRecord::Base
  include Addresseable

  default_scope { order("created_at DESC") }

  has_many :events
  has_many :jobs

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :city, :email_visible, :github, :postal_code,
                  :street, :twitter, :username, :website

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :postal_code, presence: true

  def to_s
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    { locale: I18n.locale }
  end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
  load_and_authorize_resource
  def create
    respond_with(EventCreator.new(current_user, params[:event]).execute)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < InheritedResources::Base
  load_and_authorize_resource
  def create
    respond_with(JobCreator.new(current_user, params[:job]).execute)
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end

  def users
    @users = User.geocoded
  end

  def jobs
    @jobs = Job.geocoded
  end

  def events
    @events = Event.geocoded
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  def create
    respond_with(UserCreator.new(params[:user]).execute)
  end
end

app/helpers/application_helper.rb
#encoding=utf-8
module ApplicationHelper
  def alert_box(class_name, message)
    if message.present?
      message_tag = content_tag(:div, message)
      button_tag = content_tag(:button, "x", class: "close", data: { dismiss: "alert" })
      content_tag :div, button_tag + message_tag , class: "alert alert-#{class_name}"
    end
  end

  def avatar_url(user, size=100)
    default_url = "http://#{request.host}:#{request.port}/assets/guest.png"
    return default_url if user.nil? || !Rails.env.production?
    avatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{avatar_id}.png" \
      "?s=#{size}&d=#{CGI.escape(default_url)}"
  end

  def image_for(user)
    image_tag(avatar_url(user, 76), class: 'avatar')
  end

  def excerpt(text)
    raw(truncate(sanitize(text), length: 200))
  end

  def markdown(code)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                       autolink: true,
                                       no_intra_emphasis: true,
                                       fenced_code_blocks: true)
    markdown.render(code)
  end

  def link_to_locales
    text = I18n.locale == :en ? "Version Française" : "English Version"
    locale = I18n.locale == :en ? 'fr' : 'en'
    link_to raw("<i class='icon-flag'></i> #{text}"), "/#{locale}/"
  end

  def browser_title(title)
    content_for(:title) { title }
  end

  def browser_description(description)
    content_for(:description) { description }
  end

  def browser_keywords(keywords)
    content_for(:keywords) { keywords }
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def link_for_delete(model)
    if can?(:delete, model)
      link_to "Delete",
        model,
        method: :delete,
        data: { confirm: "Are you sure?" },
        class: 'btn btn-danger'
    end
  end

  def link_for_edit(model)
    if can?(:update,model)
      link_to "Edit", edit_polymorphic_path(model), class: 'btn'
    end
  end

  def form_actions_for(model)
    if can?(:manage, model)
      link_for_edit = link_for_edit(model) || ""
      link_for_delete = link_for_delete(model) || ""
      content_tag(:div, class: "form-actions") do
        link_for_edit + link_for_delete
      end
    end
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def email_for(user)
    if user.email_visible?
      content_tag(:p) do
        link_to user.email, "mailto:#{user.email}"
      end
    end
  end

  def twitter_for(user)
    if user.twitter
      content_tag(:p) do
        link_to user.twitter, "http://twitter.com/#{user.twitter}"
      end
    end
  end

  def github_for(user)
    if user.github
      content_tag(:p) do
        link_to user.github, "https://github.com/#{user.github}"
      end
    end
  end

  def website_for(user)
    if user.website
      content_tag(:p) do
        link_to user.website, user.website
      end
    end
  end
end

app/views/events/_event.html.haml
.accordion-group
  .accordion-heading
    %a.accordion-toggle{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapse#{event.id}"}
      %h5
        =event.title
    %div{:id => "collapse#{event.id}", class: "accordion-body collapse"}
      .accordion-inner
        / Para
        %span
          %i.icon-calendar
          = t('.date', date: event.date.strftime("%Y-%m-%d"))
          %i.icon-home
          = t('.location', city: event.city)
        %p= raw(markdown(excerpt(event.description)))
        = link_to t('shared.read_more'), event

app/views/events/_form.html.haml
= simple_form_for @event do |f|
  = f.input :title
  = f.input :date
  = f.input :website
  = f.input :street
  = f.input :postal_code
  = f.input :city
  = f.input :description, as: :markdown, label_html: { for: 'wmd-input' }
  = f.button :submit, "Submit"

app/views/events/edit.html.haml
.well
  %h2= t('.edit_event')
  = render "form"

app/views/events/index.html.haml
.events
  .hero
    %h3
      %span= t('shared.events')
  - if can?(:create, Event)
    .well
      = link_to t('.add_new'), new_event_path, class: "btn"
  #accordion2.accordion
    =render @events

app/views/events/new.html.haml
.well
  %h2= t('.add_new_event')
  = render "form"

app/views/events/show.html.haml
.well
  %h1= @event
  %p= t('.date', date: @event.date.strftime("%Y-%m-%d"))
  %p= t('.address',
          street: @event.street,
          postal_code: @event.postal_code,
          city: @event.city)
  - if @event.website.present?
    %p= raw(t('.website', link: link_to(@event.website, @event.website)))
  %p= raw(t('.description', description: markdown(@event.description)))
  =form_actions_for(@event)

app/views/groups/index.html.haml
.main-content
  .main-box
    %iframe#forum_embed{:scrolling => "no", :src => "javascript:void(0)"}

app/views/jobs/_form.html.haml
= simple_form_for @job do |f|
  %fieldset
    .jobFormLeft
      = f.input :post_name
      = f.input :company_name
      = f.input :email
      = f.input :website
    .jobFormRight
      = f.input :city
      = f.input :street
      = f.input :postal_code
  = f.input :description, as: :markdown, label_html: { for: 'wmd-input' }
  = f.button :submit, t('shared.submit')

app/views/jobs/_job.html.haml
.rblock
  .row
    .span3
      %h4= job.post_name
    .span9
      .rinfo
        %h5= job.company_name
        .rmeta= job.created_at.strftime("%Y-%m-%d")
        %p= raw(markdown(excerpt(job.description)))
        = link_to t('shared.read_more'), job

app/views/jobs/edit.html.haml
.well
  %h2= t('.edit_job')
  =render "form"

app/views/jobs/index.html.haml
.resume
  .row
    .span9
      - if can?(:create, Job)
        .well
          = link_to t('.add_new'), new_job_path, class: "btn"
      = render @jobs

app/views/jobs/new.html.haml
.well
  %h2= t('.add_new_job')
  =render "form"

app/views/jobs/show.html.haml
.well
  %h1= @job.post_name
  %p= t('.company_name', company: @job.company_name)
  %p= raw(t('.email', link: link_to(@job.email, "mailto:#{@job.email}")))
  %p= t('.address',
          street: @job.street,
          postal_code: @job.postal_code,
          city: @job.city)
  - if @job.website.present?
    %p= raw(t('.website', link: link_to(@job.website, @job.website)))
  %p= raw(markdown(@job.description))
  %p= t('.creation_date', date: @job.created_at.strftime("%Y-%m-%d"))
  =form_actions_for(@job)

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    - if content_for?(:description)
      %meta{name: "description", content: content_for(:description)}
    - if content_for?(:keywords)
      %meta{name: "keywords", content: content_for(:keywords)}
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? "#{yield(:title)} - RubyQuebec" : "RubyQuebec"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = javascript_include_tag "application"
    -if current_user.try(:admin?)
      = javascript_include_tag "admin"
    = analytics_init if Rails.env.production?
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")

    - if I18n.locale == :fr
      :javascript
        window.locale = 'fr'
    - else
      :javascript
        window.locale = 'en'

  %body
    / Header starts
    %header
      .container
        .row
          .span4
            / Logo and site link
            .logo
              %h1
                %a{:href => "/"} RubyQuebec<span class="color">.</a>
          .span4.offset4
            .list
              -if current_user
                = link_to t('.sign_out'),
                        destroy_user_session_path,
                        method: :delete
                %hr/
                = link_to t('.edit_account'),
                        edit_user_registration_path(current_user)
                %hr/
                = link_to t('.delete_account'),
                        "/users",
                        method: :delete,
                        data: { confirm: t('shared.are_you_sure') }
              -else
                = link_to t('.sign_in'), new_user_session_path
                %hr/
                = link_to t('.sign_up'), new_user_registration_path
    / Header ends
    / Navigation Starts
    / Note down the syntax before editing. It is the default twitter bootstrap navigation
    .navbar
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            Menu
          .nav-collapse.collapse
            %ul.nav
              %li= link_to t('shared.events'),  events_path
              %li= link_to t('shared.jobs'),    jobs_path
              %li= link_to t('shared.users'),   users_path
              %li= link_to t('shared.map'),     maps_path
              %li= link_to t('shared.group'),   groups_path
            %ul.nav.pull-right
              %li= link_to_locales
    / Navigation Ends
    / Content strats
    .content
      .container
        .row
          .span3
            - MenuPresenter.categories.each do |category|
              .sidebar
                .widget
                  %h4= category.title
                  %ul
                    - category.pages.each do |page|
                      %li= link_to page.title, minimalist.page_path(page)
          .span9
            = alert_box("success", flash[:notice])
            = alert_box("error", flash[:error])
            = alert_box("alert", flash[:alert])
            =yield
    / Content ends
    / Footer
    %footer
      .container
        .row
          .span12
            %p.copy
              / Copyright information. You can remove my site link.
              Copyright &copy; RubyQuebec
              | Designed by
              %a{:href => "http://responsivewebinc.com"} Responsive Web Design

app/views/maps/index.html.haml
.well
  %form{:id => "map_filters"}
    - [[:jobs,"Jobs", "jobs.png"],[:users,"Utilisateurs", "users.png"],[:events,"Événements", "events.png"]].each do |filter|
      %label{class: 'checkbox inline filter-label'}
        %input{:type => 'checkbox', :name => filter.first, :id => "filter_#{filter.first}", :checked => true}
          = filter.second
        %img{src: "/assets/maps/#{filter.third}", class: 'filter-icon'}
.well
  #theMap
    %div{:id => "map_canvas"}

app/views/minimalist_cms/pages/show.html.haml
- browser_title @page.title
- browser_description @page.meta_description
- browser_description @page.meta_keywords
= editable(@page) { @page.body }
.bor
.main-content
  .row
    .span3
      .main-box
        %h4= t('shared.events')
        - EventPresenter.latest(5).each do |event|
          %p= link_to event.title, event
        .link_index= link_to t('.view_all_events'), events_path
    .span3
      .main-box
        %h4= t('shared.jobs')
        - JobPresenter.latest(5).each do |job|
          %p= link_to job.post_name, job
        .link_index= link_to t('.view_all_jobs'), jobs_path
    .span3
      .main-box
        %h4= t('shared.members')
        - UserPresenter.latest(5).each do |user|
          %p= link_to user.username, user
        .link_index= link_to t('.view_all_users'), users_path

app/views/users/_user.html.haml
.span2.serv
  = raw(link_to(image_tag(avatar_url(user, 40)), user))
  .userInformations
    %p= link_to(user, user)
    %p= link_to(user.email, user) if user.email_visible?
    %p= link_to(user.twitter, user) if user.twitter.present?
    %p= link_to(user.github, user) if user.github.present?

app/views/users/index.html.haml
.hero
  %h3
    %span= t('.member_list')
- @users.each_with_index do |user, index|
  =render user

app/views/users/show.html.haml
.well
  #userPage
    .avatar= raw(image_tag(avatar_url(@user)))
    .userDescriptionLeft
      %p= t('.username', username: @user)
      = email_for(@user)
      = twitter_for(@user)
      = github_for(@user)
      = website_for(@user)
    .userDescriptionRight
      -if @user.city.present?
        %p= t('.city', city: @user.city)
      %p= t('.registration_date', date: @user.created_at.strftime("%Y-%m-%d"))